language: elixir

elixir:
  - 1.7.3

services:
  - postgresql

addons:
  postgresql: "9.5"

env:
  global:
    - PSQL_USER=postgres
    - PSQL_DB=travis
    - MIX_ENV=test

script:
  - mix do local.hex --force
  - mix deps.get
  - mix test
  - mix credo

cache:
  directories:
    - _build
    - deps
